ifeq ($(CONFIG_FINGERPRINT_GOODIX_GF_TEE),y)
obj-y	+=  gf/
endif
ifeq ($(CONFIG_FINGERPRINT_GOODIX_GF616),y)
obj-y	+=  gf616/
endif

ifeq ($(CONFIG_FINGERPRINT_GOODIX_GF516M),y)
obj-y	+=  gf516m/
endif
ifeq ($(CONFIG_FINGERPRINT_FPC_ISEE),y)
obj-y	+=  fpc/
endif
