
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_CM36652_NEW),y)
obj-y	+=  cm36652-new/
endif

#Added start by wenshengfan,2015/12/8
ifeq ($(CONFIG_MTK_ROHM_BH1745),y)
obj-y += bh1745/
endif
#Added end by wenshengfan,2015/12/8
